var express = require('express');
var router = express.Router();
const { debug, addMovie, initSession } = require("../lib");
const { addMovie, matchRecomendedMovies } = require("../model/node/movie");
const { addProfile , matchSimilarProfiles} = require("../model/node/profile");
const { addRating } = require("../model/edge/rated");
const dotenv = require('dotenv');
dotenv.config();
const { URI, USER, PASSWORD } = process.env;

const { driver, session } = initSession(URI, USER, PASSWORD);

router.post('/create-movie', async function (req, res, next) {
    const { title, released, tagline } = req.body;
    const movieId = await addMovie(session, { title, released, tagline });
    const response = { movieId };
    debug(movieId);
    res.send(response);
});

//TODO error handling
router.post('/rank/:movieId', async function (req, res, next) {
    const { profileUri, raiting } = req.body;
    const movieId = req.params.movieId;
    // TODO check if profile exists using profileUri
    // TODO if not add Profile node
    await addProfile(session,profileUri);
    const response = await addRating(session,movieId,profileUri, raiting);
    debug(response);
    // TODO should i close the session here ?
    res.send(response);
});
// TODO rewrite function to use :facebookProfileUri instead of autogenerated id
router.get('/suggest-movies/:profileAutoId', async function (req, res, next) {
    const recomendedMovieTitles = await matchRecomendedMovies(session, { profileAutoId });
    debug(recomendedMovieTitles);
    res.send(recomendedMovieTitles);
});
// TODO rewrite function to use :facebookProfileUri instead of autogenerated id
router.get('/suggest-similar-profiles/:profileAutoId', async function (req, res, next) {
    const recomendedProfiles = await matchSimilarProfiles(session, { profileAutoId });
    debug(recomendedProfiles);
    res.send(recomendedProfiles);
});
module.exports = router;
